export const config = {
   menu :[
     {
       name:'资金概览',
       url:'/dashboard',
       icon:'icon-speedometer'
     },
     {
       name:'举报管理',
       url:'/against',
       icon:'icon-puzzle'
     },
     {
       name:'用户管理',
       url:'/user',
       icon:'icon-star'
     }/*,
     {
       name:'用户管理',
       icon:'icon-star',
       children:[
         {
           name:'用户列表',
           url:'/user/list',
           icon:'icon-star'
         }
       ]
     }*/
   ]
}
